---
semi: true
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: true
trailingComma: all
bracketSpacing: true
bracketSameLine: false
arrowParens: always
proseWrap: preserve
htmlWhitespaceSensitivity: css
singleAttributePerLine: true
insertPragma: false
requirePragma: false
printWidth: 120
plugins:
  - '@ianvs/prettier-plugin-sort-imports'
  - 'prettier-plugin-tailwindcss'
importOrder:
  - ^react$
  - ''
  - <THIRD_PARTY_MODULES>
  - ''
  - ^@/.*$
  - ''
  - '^[.]'
  - ''
  - '^.+\\.s?css$'
importOrderParserPlugins:
  - typescript
  - jsx
  - decorators-legacy
importOrderTypeScriptVersion: 5.0.0
importOrderCaseSensitive: false
tailwindStylesheet: './src/app/global.css'

overrides:
  - files: '*.yml'
    options:
      tabWidth: 2
  - files: '*.md'
    options:
      tabWidth: 1
